-- update catalog status
UPDATE COV05_HEALTH_STATUS SET status= 'SIN_CONFIRMAR' WHERE id=1;
UPDATE COV05_HEALTH_STATUS SET status= 'CON_SINTOMAS' WHERE id=2;
UPDATE COV05_HEALTH_STATUS SET status= 'CONTAGIADO' WHERE id=3;
UPDATE COV05_HEALTH_STATUS SET status= 'NO_CONTAGIADO' WHERE id=4;